- src/components/BuilderComponents/StyledChecks.js
- src/components/BuilderComponents/TextAndImageBlock.js
- src/components/all.scss
- src/pages/custom/custom-page.md
- src/pages/custom/test.md
- src/pages/school-programs/seasonal-programs.md
- static/admin/config.yml
Fixed box-shadow on images
Styled checks can now have their color and direction changed
Aliases on config to DRY up the long file...
> General fixes

- gatsby-node.js
- src/components/BasicHeader.js
- src/components/CourseOfferings.js
- src/pages/experience-levels/advanced-code.md
- src/pages/experience-levels/beginner-code.md
- src/pages/experience-levels/girlcode.md
- src/pages/experience-levels/half-day-camp.md
- src/pages/experience-levels/high-school-code.md
- src/pages/experience-levels/mini-camp.md
- src/pages/experience-levels/young-beginner-code.md
- src/templates/locations.js
- static/admin/config.yml
This relies on a new `categoryId` from the server (https://github.com/privateprep/dashboard/pull/6161)
The string on names matching wasn't reliably working out for me
I wasn't able to actually test this in the UI yet as the git branch has changed from "master" to "main" and I missed updating this config when that happened earlier today
As such I'm thinking "deploy and then double check it works"
> Update branch + Class Category Ids

- src/pages/classes.js
- src/templates/locations.js
other side of https://github.com/privateprep/dashboard/pull/6177
> Fixup online location

- src/components/ClassCards.scss
- src/components/CtaContact.css
- src/components/Footer.scss
- src/components/all.scss
- src/pages/classes.js
- src/pages/classes.scss
- src/templates/styles/locations.scss
- src/utils/helpers.js
Improved signup side of the site to fit mobile, tablet, and desktop sizes. 
On mobile screens, we're using a details element to hide the large filter list. In the future, we'll replace it with something more robust.
> Mobile view

- src/components/CourseOfferings.js
This abstracts out the filters in case, say, a location and semester
pairing yields no results
> Ensures no content shown

- gatsby-browser.js
- src/components/CourseOfferings.js
- src/components/CourseOfferings.scss
- src/components/FilterForm.js
- src/components/FilterForm.scss
- src/hooks/useFilters.js
- src/pages/classes.js
- src/pages/classes.scss
Ensures form filter state is pushed to url
> Filter form

- src/components/ClassPanel.js
- src/components/ClassPanel.scss
- src/components/CourseOfferings.js
- src/components/Footer.scss
- src/pages/classes.js
- src/templates/location.js
- src/templates/locations.js
- src/templates/styles/location.scss
- src/templates/styles/locations.scss
- src/utils/helpers.js
Getting launch ready!
See commits for additional info. Style fixes, omitting semester filter on Location show page because of mismatched data, Location show page layout and color improvements.
> Small fixes

- src/components/sign_up/OverviewPage.js
- src/templates/styles/locations.scss
Fix class semester name on signup page.
Fix color on +/- of Location Pane map.
> General improvements

- src/cms/preview-templates/AboutUsPreview.js
- src/cms/preview-templates/CustomPagePreview.js
- src/cms/preview-templates/ExperienceLevelsPreview.js
- src/cms/preview-templates/SchoolProgramsPreview.js
- src/components/BuilderComponents/Buttons.js
- src/components/BuilderComponents/HeaderAndMarkDownBlock.js
- src/components/BuilderComponents/TextAndImageBlock.js
- src/pages/about-us/this-is-a-test.md
- src/pages/blog/index.js
- src/pages/custom/index.js
- src/templates/about-us.js
- src/templates/blog-post.js
- src/templates/custom-page.js
- src/templates/locations.js
- src/templates/partnerships.js
- src/templates/school-programs.js
- static/admin/config.yml
Inclusion of optional button fields to various component builders for added flexibility.
> Builder improvements

- src/pages/about-us/about-us.md
- src/pages/about-us/this-is-a-test.md
- static/admin/config.yml
I was testing how the relational fields worked in netlify CMS and forgot to remove it here.
> Remove relational field used for testing.

- gatsby-config.js
- package.json
- src/templates/index-page.js
- static/ad-words-event.js
- static/ad-words-tracking.js
- yarn.lock
I left out code to extract env variables 🤦‍♂️
This puts it in and also switches our gtag manager plugin that has more features and is compatible with GA-4. Also supports specific event handling features that I'll do more research on.
> New gtag management

- gatsby-config.js
Prevented me from debugging and seeing analytics data.
> Remove optional DNT flag.

- src/components/BuilderComponents/Reviews.js
- src/components/BuilderComponents/StyledChecks.js
- src/components/all.scss
- static/admin/config.yml
- Makes heading optional for reviews
- Removes top margin on first <p> elements so they align with headers
- Fix up style alignment, sizing
- Replaces default link color
> General improvements 9 7

- src/components/all.scss
- src/templates/template_exports/blog-post-template.js
Make's blogs mobile friendly!
Note that the tags and the menu bar are too similar. This will go away when the real menu is launched and tucked away in a burger menu.
> Blog mobile styling

- src/components/BuilderComponents/Buttons.js
- src/components/BuilderComponents/Iframe.js
- src/components/BuilderComponents/SideBySide.js
- src/components/BuilderComponents/index.js
- src/components/BuilderComponents/stories/Iframe.stories.js
- src/components/BuilderComponents/styles/Iframe.scss
- src/components/BuilderComponents/styles/SideBySide.scss
- src/components/PageBuilder.js
- src/components/all.scss
- src/pages/custom/custom-page.md
- src/pages/custom/test.md
- src/templates/custom-page.js
- static/admin/config.yml
This is a preview of what's to come. Needs some styling adjustments to ensure proper centering
> Iframe component

- src/components/all.scss
- src/components/sign_up/OverviewPage.js
- src/components/sign_up/formFields.js
- src/components/sign_up/styles/sign-up.scss
Starting January 31st, all students are required to have received at least one dose of the vaccine in order to attend in-person classes. 
I've added a notice/question to all in-person classes that ask the client to confirm vaccine status. If they try to avoid the question or mark no, the yup validation catches it and they're blocked from proceeding. It also triggers a red warning stating the vaccine requirement and they're advised to check out our online classes.
> Vaccine check

- src/cms/preview-templates/PartnershipsPreview.js
- src/pages/partnerships/partnerships.md
- src/pages/partnerships/testing.md
- src/templates/partnerships.js
- src/templates/template_exports/partnerships-template.js
- static/admin/config.yml
Becky was having issues with the pagebuilder throwing an error (likely an issue with the hero image.) This should fix it!
> Partnerships

- static/admin/config.yml
Impressed this is my first time doing this! Forgot to switch the config file back to the main branch after tweaking programs
> Switch config back to main branch.

- src/components/Atoms/styles/Iframe.scss
- src/components/BuilderComponents/Buttons.js
- src/components/BuilderComponents/styles/BuilderComponent.scss
- src/components/BuilderComponents/styles/Buttons.scss
- src/templates/custom-page.js
- src/templates/locations.js
- src/templates/partnerships.js
- src/templates/programs.js
> Iframe fix

- src/components/Atoms/styles/ButtonLink.scss
- src/components/BuilderComponents/styles/TextOnly.scss
- src/components/Layout.js
- src/components/Navbar.scss
- src/components/all.scss
Various style tweaks plus updated navbar to reflect marketing plan
> Navbar update

- src/pages/programs/our-programs.md
- src/templates/programs.js
Hooks up the last remaining page!
> Hook up summer camps to programs.

- gatsby-config.js
- package.json
- src/pages/404.js
- src/utils/honeybadger.js
- yarn.lock
Testing HB
Not the prettiest, but gets the job done at the moment for catching any major errors and any broken links!
> Testing 404 error handling.

- static/_redirects
A redirects file needs to be in the public directory to be picked up by Netlify. Testing to see if this works on a real deploy.
Locally the file is stored in /static which doesn't allow the redirect to work properly (I think).
> Include redirects file.

- src/components/BuilderComponents/TextAndImageBlock.js
- src/components/Layout.js
- src/components/PreviewCompatibleImage.js
- static/_redirects
Becky finished this page and it's ready to be linked. Allowing preview build since Dashboard went down and blocked several of Becky's changes from going through.
> Add code 4 change to menu

- src/components/sign_up/styles/FormikRadioButtonGroup.css
This made it impossible to tell which radio button was selected.
> Fix zero width radio button on mobile.

- src/components/Testimonials.js
- src/components/Testimonials.scss
- src/templates/styles/IndexPage.scss
- src/templates/template_exports/index-page-template.js
Before:
After:
note: precise things might have shifted _slightly_ since screen shots taken
> Testimonial height

- static/_redirects
Adds a redirect from the classes subdomain to our primary one
https://answers.netlify.com/t/redirect-from-netlify-subdomain-to-custom-primary-domain-not-working/10458/4
> Add classes subdomain redirect to primary.

- yarn.lock
Engables cache of DSG.
https://www.netlify.com/blog/2021/09/16/run-gatsby-4-with-dsg-and-ssr-on-netlify-today/
> Upgrade gatsby-plugin--netlify.

- src/components/sign_up/formFields.js
This removes both the <5 and <5.75 age limits that were put in place. 
This was requested by Maddy as there are upcoming preschool sessions.
> Remove under 5 age restriction and warning

- src/components/sign_up/formFields.js
This data was never used for reporting as we said we were going to.
> Remove racial identity from sign up form.

- src/components/CollectRetrievedPayment.js
- src/components/sign_up/index.js
This supports deferred payment intents on the dashboard. This PR
- adds support for calculation and display of credit card fee, if applicable
- adds support for new dashboard routes which handle payment intent creation after the form has been submitted
> Add CC fee into abandonded cart checkout flow
